from pathlib import Path

import pandas as pd


OUTPUT_DIR = Path(__file__).parent

B2B_SERVICE_COLUMNS = [
    "first_name",
    "last_name",
    "company_name",
    "job_title",
    "email",
    "phone",
    "website",
    "industry",
    "source",
    "location",
    "deal_value",
    "budget_range",
    "interest_level",
    "timeline",
    "notes",
]

REAL_ESTATE_COLUMNS = [
    "first_name",
    "last_name",
    "email",
    "phone",
    "location",
    "property_type",
    "budget_range",
    "timeline",
    "source",
    "interest_level",
    "notes",
]

RECRUITMENT_COLUMNS = [
    "first_name",
    "last_name",
    "company_name",
    "job_title",
    "email",
    "phone",
    "hiring_need",
    "role_type",
    "urgency",
    "source",
    "location",
    "notes",
]


B2B_SERVICE_LEADS = [
    {
        "first_name": "Maya",
        "last_name": "Patel",
        "company_name": "Northstar Homes",
        "job_title": "Operations Director",
        "email": "maya.patel@northstarhomes.example",
        "phone": "+1-415-555-0134",
        "website": "https://northstarhomes.example",
        "industry": "Property Management",
        "source": "Referral",
        "location": "San Francisco, CA",
        "deal_value": 18500,
        "budget_range": "15k-25k",
        "interest_level": "High",
        "timeline": "This quarter",
        "notes": "Asked for a proposal after a referral and mentioned their team still tracks follow-up in a shared spreadsheet.",
    },
    {
        "first_name": "Jordan",
        "last_name": "Lee",
        "company_name": "BrightPath Marketing",
        "job_title": "Founder",
        "email": "jordan.lee@brightpath.example",
        "phone": "",
        "website": "https://brightpath.example",
        "industry": "Marketing Agency",
        "source": "Inbound form",
        "location": "Austin, TX",
        "deal_value": 9200,
        "budget_range": "5k-10k",
        "interest_level": "Medium",
        "timeline": "30-60 days",
        "notes": "Needs help cleaning CRM data before a new outbound campaign.",
    },
    {
        "first_name": "Elena",
        "last_name": "Garcia",
        "company_name": "HarborPoint Logistics",
        "job_title": "Head of Sales",
        "email": "",
        "phone": "+1-206-555-0188",
        "website": "https://harborpointlogistics.example",
        "industry": "Logistics",
        "source": "LinkedIn",
        "location": "Seattle, WA",
        "deal_value": 14500,
        "budget_range": "10k-20k",
        "interest_level": "High",
        "timeline": "This month",
        "notes": "Requested pricing by phone and mentioned the team is evaluating two vendors.",
    },
    {
        "first_name": "Noah",
        "last_name": "Williams",
        "company_name": "Greenline Dental Group",
        "job_title": "Practice Manager",
        "email": "noah.williams@greenlinedental.example",
        "phone": "+1-312-555-0190",
        "website": "",
        "industry": "Healthcare",
        "source": "Webinar",
        "location": "Chicago, IL",
        "deal_value": 6400,
        "budget_range": "5k-10k",
        "interest_level": "Medium",
        "timeline": "Next quarter",
        "notes": "Downloaded the follow-up checklist after attending the webinar.",
    },
    {
        "first_name": "Aisha",
        "last_name": "Khan",
        "company_name": "BluePeak Advisory",
        "job_title": "Managing Partner",
        "email": "aisha.khan@bluepeak.example",
        "phone": "+1-646-555-0173",
        "website": "https://bluepeakadvisory.example",
        "industry": "Consulting",
        "source": "Partner referral",
        "location": "New York, NY",
        "deal_value": 32000,
        "budget_range": "25k-50k",
        "interest_level": "High",
        "timeline": "Immediate",
        "notes": "Has board approval and wants an onboarding plan by next week.",
    },
    {
        "first_name": "Liam",
        "last_name": "Owen",
        "company_name": "",
        "job_title": "Independent Consultant",
        "email": "liam.owen@example.com",
        "phone": "+1-303-555-0121",
        "website": "",
        "industry": "Freelance Consulting",
        "source": "Newsletter",
        "location": "Denver, CO",
        "deal_value": 2800,
        "budget_range": "Under 5k",
        "interest_level": "Low",
        "timeline": "No fixed date",
        "notes": "Asked for examples but has not defined a project yet.",
    },
    {
        "first_name": "Priya",
        "last_name": "Shah",
        "company_name": "Cedar & Co Accounting",
        "job_title": "Client Services Lead",
        "email": "priya.shah@cedaraccounting.example",
        "phone": "",
        "website": "https://cedaraccounting.example",
        "industry": "Accounting",
        "source": "Cold outreach",
        "location": "Portland, OR",
        "deal_value": 7600,
        "budget_range": "5k-10k",
        "interest_level": "Medium",
        "timeline": "60-90 days",
        "notes": "Replied with interest but asked to revisit after tax season.",
    },
    {
        "first_name": "Marcus",
        "last_name": "Brown",
        "company_name": "Launchpad SaaS",
        "job_title": "VP Revenue",
        "email": "marcus.brown@launchpadsaas.example",
        "phone": "+1-512-555-0140",
        "website": "https://launchpadsaas.example",
        "industry": "SaaS",
        "source": "Inbound form",
        "location": "Austin, TX",
        "deal_value": 41000,
        "budget_range": "25k-50k",
        "interest_level": "High",
        "timeline": "This quarter",
        "notes": "Pipeline is growing quickly and the team needs automated follow-up drafts.",
    },
    {
        "first_name": "Sarah",
        "last_name": "Miller",
        "company_name": "Evergreen Fitness Studios",
        "job_title": "Regional Manager",
        "email": "sarah.miller@evergreenfitness.example",
        "phone": "+1-702-555-0166",
        "website": "https://evergreenfitness.example",
        "industry": "Fitness",
        "source": "Trade show",
        "location": "Las Vegas, NV",
        "deal_value": 11800,
        "budget_range": "10k-20k",
        "interest_level": "Medium",
        "timeline": "30-60 days",
        "notes": "Visited the booth with the sales manager and asked for a comparison before their next budget meeting.",
    },
    {
        "first_name": "Tom",
        "last_name": "Bennett",
        "company_name": "MetroBuild Contractors",
        "job_title": "Commercial Director",
        "email": "",
        "phone": "+1-404-555-0119",
        "website": "https://metrobuild.example",
        "industry": "Construction",
        "source": "Referral",
        "location": "Atlanta, GA",
        "deal_value": 22000,
        "budget_range": "20k-30k",
        "interest_level": "High",
        "timeline": "This month",
        "notes": "Phone conversation confirmed budget, but email address still needs to be collected.",
    },
    {
        "first_name": "Rachel",
        "last_name": "Nguyen",
        "company_name": "Clearwater Legal",
        "job_title": "Marketing Manager",
        "email": "rachel.nguyen@clearwaterlegal.example",
        "phone": "+1-617-555-0181",
        "website": "https://clearwaterlegal.example",
        "industry": "Legal Services",
        "source": "Google Ads",
        "location": "Boston, MA",
        "deal_value": 13400,
        "budget_range": "10k-20k",
        "interest_level": "Medium",
        "timeline": "Next quarter",
        "notes": "Interested in lead qualification and reporting for partner meetings.",
    },
    {
        "first_name": "Daniel",
        "last_name": "Brooks",
        "company_name": "Atlas Field Services",
        "job_title": "General Manager",
        "email": "daniel.brooks@atlasfield.example",
        "phone": "",
        "website": "https://atlasfield.example",
        "industry": "Field Services",
        "source": "Cold outreach",
        "location": "Phoenix, AZ",
        "deal_value": 8700,
        "budget_range": "5k-10k",
        "interest_level": "Low",
        "timeline": "No fixed date",
        "notes": "Asked to be sent a one-page overview before scheduling a call.",
    },
    {
        "first_name": "Emily",
        "last_name": "Turner",
        "company_name": "Oak & Linen Events",
        "job_title": "Owner",
        "email": "emily.turner@oaklinen.example",
        "phone": "+1-615-555-0107",
        "website": "https://oaklinen.example",
        "industry": "Events",
        "source": "Instagram",
        "location": "Nashville, TN",
        "deal_value": 5100,
        "budget_range": "5k-10k",
        "interest_level": "Medium",
        "timeline": "60-90 days",
        "notes": "Currently tracking inquiries manually and wants a simpler follow-up process.",
    },
    {
        "first_name": "Jordan",
        "last_name": "Lee",
        "company_name": "BrightPath Marketing",
        "job_title": "Founder",
        "email": "j.lee@brightpath.example",
        "phone": "+1-512-555-0199",
        "website": "https://brightpath.example",
        "industry": "Marketing Agency",
        "source": "Webinar",
        "location": "Austin, TX",
        "deal_value": 9800,
        "budget_range": "5k-10k",
        "interest_level": "Medium",
        "timeline": "30-60 days",
        "notes": "Duplicate-looking lead from a webinar signup with a different email address.",
    },
    {
        "first_name": "Chris",
        "last_name": "Dawson",
        "company_name": "Pioneer IT Support",
        "job_title": "Sales Manager",
        "email": "chris.dawson@pioneerit.example",
        "phone": "+1-919-555-0132",
        "website": "https://pioneerit.example",
        "industry": "IT Services",
        "source": "Referral",
        "location": "Raleigh, NC",
        "deal_value": 17300,
        "budget_range": "15k-25k",
        "interest_level": "High",
        "timeline": "This quarter",
        "notes": "Wants to improve follow-up speed after missing several inbound requests.",
    },
]

REAL_ESTATE_LEADS = [
    {
        "first_name": "Olivia",
        "last_name": "Stone",
        "email": "olivia.stone@example.com",
        "phone": "+1-310-555-0144",
        "location": "Santa Monica, CA",
        "property_type": "Condo",
        "budget_range": "750k-900k",
        "timeline": "30-60 days",
        "source": "Website valuation form",
        "interest_level": "High",
        "notes": "Pre-approved and wants listings near the beach with parking.",
    },
    {
        "first_name": "Ben",
        "last_name": "Carter",
        "email": "",
        "phone": "+1-214-555-0182",
        "location": "Dallas, TX",
        "property_type": "Single-family home",
        "budget_range": "450k-550k",
        "timeline": "This quarter",
        "source": "Open house",
        "interest_level": "Medium",
        "notes": "Visited the Oak Ridge open house and asked about school districts.",
    },
    {
        "first_name": "Nora",
        "last_name": "Hughes",
        "email": "nora.hughes@example.com",
        "phone": "",
        "location": "Charlotte, NC",
        "property_type": "Townhouse",
        "budget_range": "350k-450k",
        "timeline": "60-90 days",
        "source": "Zillow inquiry",
        "interest_level": "Medium",
        "notes": "Needs a low-maintenance property and requested virtual tours.",
    },
    {
        "first_name": "Ethan",
        "last_name": "Reed",
        "email": "ethan.reed@example.com",
        "phone": "+1-503-555-0198",
        "location": "Portland, OR",
        "property_type": "Duplex",
        "budget_range": "600k-750k",
        "timeline": "This month",
        "source": "Referral",
        "interest_level": "High",
        "notes": "Investor buyer looking for rental yield and quick financing options.",
    },
    {
        "first_name": "Grace",
        "last_name": "Kim",
        "email": "grace.kim@example.com",
        "phone": "+1-415-555-0195",
        "location": "Oakland, CA",
        "property_type": "Single-family home",
        "budget_range": "900k-1.1m",
        "timeline": "Next quarter",
        "source": "Google Ads",
        "interest_level": "Low",
        "notes": "Early research stage and comparing neighborhoods.",
    },
    {
        "first_name": "Leo",
        "last_name": "Martinez",
        "email": "leo.martinez@example.com",
        "phone": "+1-602-555-0155",
        "location": "Scottsdale, AZ",
        "property_type": "Luxury home",
        "budget_range": "1.2m-1.6m",
        "timeline": "Immediate",
        "source": "Broker referral",
        "interest_level": "High",
        "notes": "Relocating for work and wants private showings this week.",
    },
    {
        "first_name": "Mia",
        "last_name": "Roberts",
        "email": "mia.roberts@example.com",
        "phone": "",
        "location": "Tampa, FL",
        "property_type": "Condo",
        "budget_range": "300k-400k",
        "timeline": "No fixed date",
        "source": "Facebook lead ad",
        "interest_level": "Low",
        "notes": "Asked for a buying guide and mortgage basics.",
    },
    {
        "first_name": "Samuel",
        "last_name": "Price",
        "email": "sam.price@example.com",
        "phone": "+1-617-555-0128",
        "location": "Cambridge, MA",
        "property_type": "Multi-family",
        "budget_range": "1.0m-1.4m",
        "timeline": "This quarter",
        "source": "Investor webinar",
        "interest_level": "Medium",
        "notes": "Interested in cap rates and renovation history.",
    },
    {
        "first_name": "Hannah",
        "last_name": "Evans",
        "email": "",
        "phone": "",
        "location": "Denver, CO",
        "property_type": "Townhouse",
        "budget_range": "500k-650k",
        "timeline": "60-90 days",
        "source": "Open house",
        "interest_level": "Medium",
        "notes": "Signed in at an open house but contact details need follow-up from the paper form.",
    },
    {
        "first_name": "Victor",
        "last_name": "Chen",
        "email": "victor.chen@example.com",
        "phone": "+1-206-555-0137",
        "location": "Bellevue, WA",
        "property_type": "Single-family home",
        "budget_range": "950k-1.2m",
        "timeline": "30-60 days",
        "source": "Website inquiry",
        "interest_level": "High",
        "notes": "Needs a home office and asked for commute times to downtown Seattle.",
    },
    {
        "first_name": "Olivia",
        "last_name": "Stone",
        "email": "ostone@example.com",
        "phone": "+1-310-555-0144",
        "location": "Santa Monica, CA",
        "property_type": "Condo",
        "budget_range": "750k-900k",
        "timeline": "30-60 days",
        "source": "Open house",
        "interest_level": "High",
        "notes": "Duplicate-looking lead captured again at an open house.",
    },
    {
        "first_name": "Isabella",
        "last_name": "Wright",
        "email": "isabella.wright@example.com",
        "phone": "+1-305-555-0164",
        "location": "Miami, FL",
        "property_type": "Waterfront condo",
        "budget_range": "800k-1.0m",
        "timeline": "This month",
        "source": "Referral",
        "interest_level": "High",
        "notes": "Wants buildings with strong rental policy and concierge service.",
    },
]

RECRUITMENT_LEADS = [
    {
        "first_name": "Amelia",
        "last_name": "Foster",
        "company_name": "Vertex Payments",
        "job_title": "People Director",
        "email": "amelia.foster@vertexpayments.example",
        "phone": "+44 20 5555 0141",
        "hiring_need": "Senior backend engineer",
        "role_type": "Permanent",
        "urgency": "High",
        "source": "Referral",
        "location": "London, UK",
        "notes": "Needs three-person shortlist within two weeks for a new payments platform team.",
    },
    {
        "first_name": "Theo",
        "last_name": "Barker",
        "company_name": "CloudNest Analytics",
        "job_title": "CTO",
        "email": "theo.barker@cloudnest.example",
        "phone": "",
        "hiring_need": "Data engineer",
        "role_type": "Contract",
        "urgency": "Medium",
        "source": "LinkedIn",
        "location": "Manchester, UK",
        "notes": "Contract likely starts next month, rate range still being approved.",
    },
    {
        "first_name": "Sophie",
        "last_name": "Grant",
        "company_name": "Aster Health",
        "job_title": "Talent Lead",
        "email": "",
        "phone": "+44 161 555 0122",
        "hiring_need": "Product manager",
        "role_type": "Permanent",
        "urgency": "High",
        "source": "Inbound form",
        "location": "Leeds, UK",
        "notes": "Left a phone number only and asked for healthcare product experience.",
    },
    {
        "first_name": "James",
        "last_name": "Walker",
        "company_name": "Northbridge Capital",
        "job_title": "Operations Partner",
        "email": "james.walker@northbridge.example",
        "phone": "+44 20 5555 0177",
        "hiring_need": "Finance operations manager",
        "role_type": "Permanent",
        "urgency": "Medium",
        "source": "Conference",
        "location": "London, UK",
        "notes": "Building portfolio operations team and wants salary benchmarks.",
    },
    {
        "first_name": "Freya",
        "last_name": "Lewis",
        "company_name": "",
        "job_title": "Founder",
        "email": "freya.lewis@example.com",
        "phone": "+44 117 555 0185",
        "hiring_need": "First sales hire",
        "role_type": "Permanent",
        "urgency": "Low",
        "source": "Newsletter",
        "location": "Bristol, UK",
        "notes": "Early-stage founder asking about timing and fee structure.",
    },
    {
        "first_name": "Omar",
        "last_name": "Hassan",
        "company_name": "Railway Digital",
        "job_title": "Engineering Manager",
        "email": "omar.hassan@railwaydigital.example",
        "phone": "+44 121 555 0130",
        "hiring_need": "DevOps engineer",
        "role_type": "Contract-to-permanent",
        "urgency": "High",
        "source": "Referral",
        "location": "Birmingham, UK",
        "notes": "Existing team is overloaded and wants candidates with Kubernetes experience.",
    },
    {
        "first_name": "Lucy",
        "last_name": "Henderson",
        "company_name": "Studio Nine Creative",
        "job_title": "Managing Director",
        "email": "lucy.henderson@studionine.example",
        "phone": "",
        "hiring_need": "Account director",
        "role_type": "Permanent",
        "urgency": "Medium",
        "source": "Cold outreach",
        "location": "Edinburgh, UK",
        "notes": "Replied that they may replace a senior account lead after a client transition.",
    },
    {
        "first_name": "Nathan",
        "last_name": "Cole",
        "company_name": "Beacon Cyber",
        "job_title": "CEO",
        "email": "nathan.cole@beaconcyber.example",
        "phone": "+44 20 5555 0169",
        "hiring_need": "Security sales director",
        "role_type": "Permanent",
        "urgency": "High",
        "source": "Inbound form",
        "location": "London, UK",
        "notes": "Has budget signed off and wants candidates with enterprise security contacts.",
    },
    {
        "first_name": "Sophie",
        "last_name": "Grant",
        "company_name": "Aster Health",
        "job_title": "Talent Lead",
        "email": "s.grant@asterhealth.example",
        "phone": "+44 161 555 0122",
        "hiring_need": "Product manager",
        "role_type": "Permanent",
        "urgency": "High",
        "source": "Referral",
        "location": "Leeds, UK",
        "notes": "Duplicate-looking lead with a different email source from the same hiring need.",
    },
    {
        "first_name": "Callum",
        "last_name": "Price",
        "company_name": "Summit Retail Group",
        "job_title": "HR Business Partner",
        "email": "callum.price@summitretail.example",
        "phone": "+44 113 555 0114",
        "hiring_need": "Regional operations manager",
        "role_type": "Permanent",
        "urgency": "Medium",
        "source": "Webinar",
        "location": "Leeds, UK",
        "notes": "Interested in market mapping before opening the formal search.",
    },
    {
        "first_name": "Imogen",
        "last_name": "Scott",
        "company_name": "Marble Legal Tech",
        "job_title": "COO",
        "email": "imogen.scott@marblelegaltech.example",
        "phone": "+44 20 5555 0180",
        "hiring_need": "Customer success manager",
        "role_type": "Permanent",
        "urgency": "Low",
        "source": "Partner referral",
        "location": "London, UK",
        "notes": "Planning ahead for a new customer success function after funding closes.",
    },
    {
        "first_name": "Ryan",
        "last_name": "Morris",
        "company_name": "Harbor Labs",
        "job_title": "Head of Product",
        "email": "ryan.morris@harborlabs.example",
        "phone": "",
        "hiring_need": "UX researcher",
        "role_type": "Contract",
        "urgency": "Medium",
        "source": "LinkedIn",
        "location": "Remote, UK",
        "notes": "Needs discovery research support for a twelve-week product validation project.",
    },
]


def build_dataframe(rows: list[dict[str, object]], columns: list[str]) -> pd.DataFrame:
    dataframe = pd.DataFrame(rows, columns=columns)
    if list(dataframe.columns) != columns:
        raise ValueError("Generated columns do not match the expected schema.")
    return dataframe


def generate_sample_data() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    b2b_dataframe = build_dataframe(B2B_SERVICE_LEADS, B2B_SERVICE_COLUMNS)
    real_estate_dataframe = build_dataframe(REAL_ESTATE_LEADS, REAL_ESTATE_COLUMNS)
    recruitment_dataframe = build_dataframe(RECRUITMENT_LEADS, RECRUITMENT_COLUMNS)

    b2b_dataframe.to_csv(OUTPUT_DIR / "b2b_service_leads.csv", index=False)
    real_estate_dataframe.to_csv(OUTPUT_DIR / "real_estate_leads.csv", index=False)
    recruitment_dataframe.to_excel(
        OUTPUT_DIR / "recruitment_leads.xlsx",
        index=False,
        sheet_name="Recruitment Leads",
    )


if __name__ == "__main__":
    generate_sample_data()
